import type { WorkspaceLanguage } from "./state/useWorkspacePreferences";

const english = {
  reviewTitle: "Review workspace",
  reviewDescription:
    "Review compatibility, human review, maintenance, changes, indexes, and the activity log across this workspace.",
  closeReview: "Close workspace review",
  reviewWorkspace: "Review workspace",
  workspaceContext: "Workspace knowledge",
  workspaceSummary: (version: string, count: number) =>
    `OKF ${version} · ${count} ${count === 1 ? "concept" : "concepts"}`,
  knowledgeSummary: (count: number) =>
    `Knowledge workspace · ${count} ${count === 1 ? "concept" : "concepts"}`,
  workspaceAttention: (count: number) =>
    `${count} need attention`,
  workspaceReady: "No required attention",
  compatibilityReview: "Compatibility",
  compatibilityReviewDescription:
    "Required OKF fixes and portability guidance for this Markdown workspace.",
  required: "Required",
  needsReview: "Needs review",
  maintenance: "Maintenance",
  changes: "Changes",
  documentContext: "Knowledge context",
  notConcept: "This file is preserved in the workspace, but it is not a Markdown knowledge concept.",
  description: "Description",
  properties: "Properties",
  type: "Type",
  status: "Status",
  trust: "Trust",
  freshness: "Freshness",
  owner: "Owner",
  tags: "Tags",
  additionalMetadata: "Additional metadata",
  notSet: "Not set",
  provenance: "Provenance",
  generatedBy: "Generated by",
  generatedAt: "Generated at",
  canonicalResource: "Canonical resource",
  sources: "Sources",
  noSources: "No source has been recorded.",
  verification: "Verification",
  latestVerification: "Latest verification",
  neverVerified: "Not verified against its sources.",
  issues: "Needs attention",
  noIssues: "No issues for this document.",
  openSource: "Open source",
};

const korean: typeof english = {
  reviewTitle: "워크스페이스 검토",
  reviewDescription:
    "워크스페이스 전체의 호환성, 사람 검토, 유지보수, 변경 사항, index, 활동 log를 검토합니다.",
  closeReview: "워크스페이스 검토 닫기",
  reviewWorkspace: "워크스페이스 검토",
  workspaceContext: "워크스페이스 지식",
  workspaceSummary: (version, count) => `OKF ${version} · Concept ${count}개`,
  knowledgeSummary: (count) => `지식 워크스페이스 · Concept ${count}개`,
  workspaceAttention: (count) => `${count}개 확인 필요`,
  workspaceReady: "필수 확인 사항 없음",
  compatibilityReview: "호환성",
  compatibilityReviewDescription:
    "현재 Markdown 워크스페이스의 OKF 필수 수정과 이식성 안내입니다.",
  required: "필수 수정",
  needsReview: "검토 필요",
  maintenance: "유지보수",
  changes: "변경 사항",
  documentContext: "지식 문맥",
  notConcept: "워크스페이스에는 보존되지만 Markdown 지식 concept는 아닌 파일입니다.",
  description: "설명",
  properties: "속성",
  type: "Type",
  status: "상태",
  trust: "신뢰",
  freshness: "최신성",
  owner: "담당자",
  tags: "태그",
  additionalMetadata: "추가 metadata",
  notSet: "설정 안 됨",
  provenance: "출처",
  generatedBy: "생성 주체",
  generatedAt: "생성 시각",
  canonicalResource: "원본 리소스",
  sources: "근거 자료",
  noSources: "기록된 근거 자료가 없습니다.",
  verification: "검증",
  latestVerification: "최근 검증",
  neverVerified: "근거 자료와 대조해 검증되지 않았습니다.",
  issues: "확인 필요",
  noIssues: "이 문서에서 확인할 문제가 없습니다.",
  openSource: "근거 자료 열기",
};

export type KnowledgePanelCopy = typeof english;

export const getKnowledgePanelCopy = (
  language: WorkspaceLanguage,
): KnowledgePanelCopy => language === "ko" ? korean : english;
