import type { WorkspaceLanguage } from "./state/useWorkspacePreferences";

export type WorkspaceActionCopy = {
  undo: string;
  originalTextNotFound: string;
  commentDeleted: string;
  commentRestored: string;
  browserSaveFailed: string;
  fileAddFailed: string;
  fileRenameFailed: string;
  fileDuplicateFailed: string;
  fileDuplicated: string;
  fileDeleteNotReady: string;
  fileDeleteFailed: string;
  fileDeleted: string;
  fileRestoreFailed: string;
  fileRestored: string;
  importRoomFailed: string;
  duplicateNotReady: string;
  folderDepth: string;
  folderAddFailed: string;
  folderDeleteNotReady: string;
  folderDeleteFailed: string;
  folderDeleted: string;
  folderRestoreFailed: string;
  folderRestored: string;
  documentMoveFailed: string;
  folderMoveInvalid: string;
  folderMoveFailed: string;
  sharedWorkspaceUpdated: string;
  documentAdded: (title: string) => string;
  documentRenamed: (previousTitle: string, title: string) => string;
};

const en: WorkspaceActionCopy = {
  undo: "Undo", originalTextNotFound: "Original text not found.", commentDeleted: "Comment deleted.", commentRestored: "Comment restored.", browserSaveFailed: "Changes couldn’t be saved in this browser.", fileAddFailed: "This document couldn’t be added to the live workspace.", fileRenameFailed: "This document couldn’t be renamed in the live workspace.", fileDuplicateFailed: "This document couldn’t be duplicated in the live workspace.", fileDuplicated: "File duplicated.", fileDeleteNotReady: "This document isn’t ready to delete yet.", fileDeleteFailed: "This document couldn’t be deleted from the live workspace.", fileDeleted: "File deleted.", fileRestoreFailed: "This document couldn’t be restored to the live workspace.", fileRestored: "File restored.", importRoomFailed: "This document couldn’t be imported into the live workspace.", duplicateNotReady: "This document isn’t ready to duplicate yet.", folderDepth: "Folders can be nested up to 32 levels.", folderAddFailed: "This folder couldn’t be added to the live workspace.", folderDeleteNotReady: "This folder isn’t ready to delete yet.", folderDeleteFailed: "This folder couldn’t be deleted from the live workspace.", folderDeleted: "Folder deleted.", folderRestoreFailed: "This folder couldn’t be restored to the live workspace.", folderRestored: "Folder restored.", documentMoveFailed: "This document couldn’t be moved in the live workspace.", folderMoveInvalid: "This folder can’t be moved there.", folderMoveFailed: "This folder couldn’t be moved in the live workspace.", sharedWorkspaceUpdated: "The shared workspace was updated.", documentAdded: (title) => `${title} was added to the room.`, documentRenamed: (previousTitle, title) => `${previousTitle} was renamed to ${title}.`,
};

const copies: Record<WorkspaceLanguage, WorkspaceActionCopy> = {
  en,
  ko: { undo: "실행 취소", originalTextNotFound: "원본 텍스트를 찾지 못했습니다.", commentDeleted: "댓글을 삭제했습니다.", commentRestored: "댓글을 복원했습니다.", browserSaveFailed: "변경 사항을 이 브라우저에 저장하지 못했습니다.", fileAddFailed: "문서를 실시간 워크스페이스에 추가하지 못했습니다.", fileRenameFailed: "실시간 워크스페이스에서 문서 이름을 바꾸지 못했습니다.", fileDuplicateFailed: "실시간 워크스페이스에서 문서를 복제하지 못했습니다.", fileDuplicated: "파일을 복제했습니다.", fileDeleteNotReady: "이 문서는 아직 삭제할 수 없습니다.", fileDeleteFailed: "실시간 워크스페이스에서 문서를 삭제하지 못했습니다.", fileDeleted: "파일을 삭제했습니다.", fileRestoreFailed: "실시간 워크스페이스에 문서를 복원하지 못했습니다.", fileRestored: "파일을 복원했습니다.", importRoomFailed: "문서를 실시간 워크스페이스로 가져오지 못했습니다.", duplicateNotReady: "이 문서는 아직 복제할 수 없습니다.", folderDepth: "폴더는 최대 32단계까지 중첩할 수 있습니다.", folderAddFailed: "실시간 워크스페이스에 폴더를 추가하지 못했습니다.", folderDeleteNotReady: "이 폴더는 아직 삭제할 수 없습니다.", folderDeleteFailed: "실시간 워크스페이스에서 폴더를 삭제하지 못했습니다.", folderDeleted: "폴더를 삭제했습니다.", folderRestoreFailed: "실시간 워크스페이스에 폴더를 복원하지 못했습니다.", folderRestored: "폴더를 복원했습니다.", documentMoveFailed: "실시간 워크스페이스에서 문서를 이동하지 못했습니다.", folderMoveInvalid: "폴더를 그 위치로 이동할 수 없습니다.", folderMoveFailed: "실시간 워크스페이스에서 폴더를 이동하지 못했습니다.", sharedWorkspaceUpdated: "공유 워크스페이스가 업데이트되었습니다.", documentAdded: (title) => `${title} 문서를 방에 추가했습니다.`, documentRenamed: (previousTitle, title) => `${previousTitle}의 이름을 ${title}(으)로 바꿨습니다.` },
  ja: { undo: "元に戻す", originalTextNotFound: "元のテキストが見つかりません。", commentDeleted: "コメントを削除しました。", commentRestored: "コメントを復元しました。", browserSaveFailed: "変更をこのブラウザーに保存できませんでした。", fileAddFailed: "ドキュメントをライブワークスペースに追加できませんでした。", fileRenameFailed: "ライブワークスペースでドキュメント名を変更できませんでした。", fileDuplicateFailed: "ライブワークスペースでドキュメントを複製できませんでした。", fileDuplicated: "ファイルを複製しました。", fileDeleteNotReady: "このドキュメントはまだ削除できません。", fileDeleteFailed: "ライブワークスペースからドキュメントを削除できませんでした。", fileDeleted: "ファイルを削除しました。", fileRestoreFailed: "ライブワークスペースにドキュメントを復元できませんでした。", fileRestored: "ファイルを復元しました。", importRoomFailed: "ドキュメントをライブワークスペースに読み込めませんでした。", duplicateNotReady: "このドキュメントはまだ複製できません。", folderDepth: "フォルダーは32階層まで作成できます。", folderAddFailed: "フォルダーをライブワークスペースに追加できませんでした。", folderDeleteNotReady: "このフォルダーはまだ削除できません。", folderDeleteFailed: "ライブワークスペースからフォルダーを削除できませんでした。", folderDeleted: "フォルダーを削除しました。", folderRestoreFailed: "ライブワークスペースにフォルダーを復元できませんでした。", folderRestored: "フォルダーを復元しました。", documentMoveFailed: "ライブワークスペースでドキュメントを移動できませんでした。", folderMoveInvalid: "フォルダーをその場所へ移動できません。", folderMoveFailed: "ライブワークスペースでフォルダーを移動できませんでした。", sharedWorkspaceUpdated: "共有ワークスペースが更新されました。", documentAdded: (title) => `${title} をルームに追加しました。`, documentRenamed: (previousTitle, title) => `${previousTitle} の名前を ${title} に変更しました。` },
  zh: { undo: "撤销", originalTextNotFound: "找不到原始文本。", commentDeleted: "已删除评论。", commentRestored: "已恢复评论。", browserSaveFailed: "无法将更改保存在此浏览器中。", fileAddFailed: "无法将文档添加到实时工作区。", fileRenameFailed: "无法在实时工作区中重命名文档。", fileDuplicateFailed: "无法在实时工作区中复制文档。", fileDuplicated: "已复制文件。", fileDeleteNotReady: "此文档暂时无法删除。", fileDeleteFailed: "无法从实时工作区删除文档。", fileDeleted: "已删除文件。", fileRestoreFailed: "无法将文档恢复到实时工作区。", fileRestored: "已恢复文件。", importRoomFailed: "无法将文档导入实时工作区。", duplicateNotReady: "此文档暂时无法复制。", folderDepth: "文件夹最多可嵌套32层。", folderAddFailed: "无法将文件夹添加到实时工作区。", folderDeleteNotReady: "此文件夹暂时无法删除。", folderDeleteFailed: "无法从实时工作区删除文件夹。", folderDeleted: "已删除文件夹。", folderRestoreFailed: "无法将文件夹恢复到实时工作区。", folderRestored: "已恢复文件夹。", documentMoveFailed: "无法在实时工作区中移动文档。", folderMoveInvalid: "无法将文件夹移动到该位置。", folderMoveFailed: "无法在实时工作区中移动文件夹。", sharedWorkspaceUpdated: "共享工作区已更新。", documentAdded: (title) => `已将 ${title} 添加到房间。`, documentRenamed: (previousTitle, title) => `已将 ${previousTitle} 重命名为 ${title}。` },
  es: { undo: "Deshacer", originalTextNotFound: "No se encontró el texto original.", commentDeleted: "Comentario eliminado.", commentRestored: "Comentario restaurado.", browserSaveFailed: "No se pudieron guardar los cambios en este navegador.", fileAddFailed: "No se pudo añadir el documento al espacio de trabajo en vivo.", fileRenameFailed: "No se pudo cambiar el nombre del documento en el espacio de trabajo en vivo.", fileDuplicateFailed: "No se pudo duplicar el documento en el espacio de trabajo en vivo.", fileDuplicated: "Archivo duplicado.", fileDeleteNotReady: "Este documento todavía no se puede eliminar.", fileDeleteFailed: "No se pudo eliminar el documento del espacio de trabajo en vivo.", fileDeleted: "Archivo eliminado.", fileRestoreFailed: "No se pudo restaurar el documento en el espacio de trabajo en vivo.", fileRestored: "Archivo restaurado.", importRoomFailed: "No se pudo importar el documento al espacio de trabajo en vivo.", duplicateNotReady: "Este documento todavía no se puede duplicar.", folderDepth: "Las carpetas pueden anidarse hasta 32 niveles.", folderAddFailed: "No se pudo añadir la carpeta al espacio de trabajo en vivo.", folderDeleteNotReady: "Esta carpeta todavía no se puede eliminar.", folderDeleteFailed: "No se pudo eliminar la carpeta del espacio de trabajo en vivo.", folderDeleted: "Carpeta eliminada.", folderRestoreFailed: "No se pudo restaurar la carpeta en el espacio de trabajo en vivo.", folderRestored: "Carpeta restaurada.", documentMoveFailed: "No se pudo mover el documento en el espacio de trabajo en vivo.", folderMoveInvalid: "La carpeta no se puede mover a esa ubicación.", folderMoveFailed: "No se pudo mover la carpeta en el espacio de trabajo en vivo.", sharedWorkspaceUpdated: "El espacio compartido se actualizó.", documentAdded: (title) => `${title} se añadió a la sala.`, documentRenamed: (previousTitle, title) => `${previousTitle} cambió de nombre a ${title}.` },
  fr: { undo: "Annuler", originalTextNotFound: "Texte d’origine introuvable.", commentDeleted: "Commentaire supprimé.", commentRestored: "Commentaire restauré.", browserSaveFailed: "Les modifications n’ont pas pu être enregistrées dans ce navigateur.", fileAddFailed: "Le document n’a pas pu être ajouté à l’espace de travail en direct.", fileRenameFailed: "Le document n’a pas pu être renommé dans l’espace de travail en direct.", fileDuplicateFailed: "Le document n’a pas pu être dupliqué dans l’espace de travail en direct.", fileDuplicated: "Fichier dupliqué.", fileDeleteNotReady: "Ce document ne peut pas encore être supprimé.", fileDeleteFailed: "Le document n’a pas pu être supprimé de l’espace de travail en direct.", fileDeleted: "Fichier supprimé.", fileRestoreFailed: "Le document n’a pas pu être restauré dans l’espace de travail en direct.", fileRestored: "Fichier restauré.", importRoomFailed: "Le document n’a pas pu être importé dans l’espace de travail en direct.", duplicateNotReady: "Ce document ne peut pas encore être dupliqué.", folderDepth: "Les dossiers peuvent être imbriqués sur 32 niveaux.", folderAddFailed: "Le dossier n’a pas pu être ajouté à l’espace de travail en direct.", folderDeleteNotReady: "Ce dossier ne peut pas encore être supprimé.", folderDeleteFailed: "Le dossier n’a pas pu être supprimé de l’espace de travail en direct.", folderDeleted: "Dossier supprimé.", folderRestoreFailed: "Le dossier n’a pas pu être restauré dans l’espace de travail en direct.", folderRestored: "Dossier restauré.", documentMoveFailed: "Le document n’a pas pu être déplacé dans l’espace de travail en direct.", folderMoveInvalid: "Le dossier ne peut pas être déplacé à cet emplacement.", folderMoveFailed: "Le dossier n’a pas pu être déplacé dans l’espace de travail en direct.", sharedWorkspaceUpdated: "L’espace partagé a été mis à jour.", documentAdded: (title) => `${title} a été ajouté à la salle.`, documentRenamed: (previousTitle, title) => `${previousTitle} a été renommé en ${title}.` },
  de: { undo: "Rückgängig", originalTextNotFound: "Originaltext nicht gefunden.", commentDeleted: "Kommentar gelöscht.", commentRestored: "Kommentar wiederhergestellt.", browserSaveFailed: "Änderungen konnten nicht in diesem Browser gespeichert werden.", fileAddFailed: "Das Dokument konnte nicht zum Live-Workspace hinzugefügt werden.", fileRenameFailed: "Das Dokument konnte im Live-Workspace nicht umbenannt werden.", fileDuplicateFailed: "Das Dokument konnte im Live-Workspace nicht dupliziert werden.", fileDuplicated: "Datei dupliziert.", fileDeleteNotReady: "Dieses Dokument kann noch nicht gelöscht werden.", fileDeleteFailed: "Das Dokument konnte nicht aus dem Live-Workspace gelöscht werden.", fileDeleted: "Datei gelöscht.", fileRestoreFailed: "Das Dokument konnte nicht im Live-Workspace wiederhergestellt werden.", fileRestored: "Datei wiederhergestellt.", importRoomFailed: "Das Dokument konnte nicht in den Live-Workspace importiert werden.", duplicateNotReady: "Dieses Dokument kann noch nicht dupliziert werden.", folderDepth: "Ordner können bis zu 32 Ebenen tief verschachtelt werden.", folderAddFailed: "Der Ordner konnte nicht zum Live-Workspace hinzugefügt werden.", folderDeleteNotReady: "Dieser Ordner kann noch nicht gelöscht werden.", folderDeleteFailed: "Der Ordner konnte nicht aus dem Live-Workspace gelöscht werden.", folderDeleted: "Ordner gelöscht.", folderRestoreFailed: "Der Ordner konnte nicht im Live-Workspace wiederhergestellt werden.", folderRestored: "Ordner wiederhergestellt.", documentMoveFailed: "Das Dokument konnte im Live-Workspace nicht verschoben werden.", folderMoveInvalid: "Der Ordner kann nicht an diesen Ort verschoben werden.", folderMoveFailed: "Der Ordner konnte im Live-Workspace nicht verschoben werden.", sharedWorkspaceUpdated: "Der geteilte Workspace wurde aktualisiert.", documentAdded: (title) => `${title} wurde zum Raum hinzugefügt.`, documentRenamed: (previousTitle, title) => `${previousTitle} wurde in ${title} umbenannt.` },
};

export const getWorkspaceActionCopy = (language: WorkspaceLanguage) => copies[language];
