import type { WorkspaceLanguage } from "../state/useWorkspacePreferences";

type WorkspaceIoCopy = {
  fileCopied: string;
  fileDownloaded: string;
  workspaceDownloaded: string;
  exportFailed: string;
  openFailed: string;
  saveOpenedWorkspaceFailed: string;
  unsupportedDrop: string;
  confirmLiveFolderDelete: string;
  liveFolderPermissionLost: string;
  liveFolderWriteConflict: string;
  liveFolderWriteFailed: string;
  liveFolderSaved: string;
  liveFolderNoChanges: string;
};

const copies: Record<WorkspaceLanguage, WorkspaceIoCopy> = {
  en: { fileCopied: "File copied.", fileDownloaded: "File downloaded.", workspaceDownloaded: "Workspace downloaded.", exportFailed: "Couldn’t export to file.", openFailed: "Couldn’t open this workspace.", saveOpenedWorkspaceFailed: "The workspace opened, but it couldn’t be saved in this browser.", unsupportedDrop: "Drop a Markdown file.", confirmLiveFolderDelete: "Also delete these files from the connected folder?", liveFolderPermissionLost: "Folder write permission was lost. Your changes remain saved in this browser.", liveFolderWriteConflict: "The connected folder changed outside Tabula. Review the conflict before saving.", liveFolderWriteFailed: "Couldn’t save changes to the connected folder.", liveFolderSaved: "Saved to the connected folder.", liveFolderNoChanges: "No changes to save." },
  ko: { fileCopied: "파일을 복사했습니다.", fileDownloaded: "파일을 다운로드했습니다.", workspaceDownloaded: "워크스페이스를 다운로드했습니다.", exportFailed: "파일로 내보내지 못했습니다.", openFailed: "이 워크스페이스를 열지 못했습니다.", saveOpenedWorkspaceFailed: "워크스페이스를 열었지만 이 브라우저에 저장하지 못했습니다.", unsupportedDrop: "Markdown 파일을 놓아주세요.", confirmLiveFolderDelete: "연결된 폴더에서도 이 파일을 삭제할까요?", liveFolderPermissionLost: "폴더 쓰기 권한이 사라졌습니다. 변경 내용은 이 브라우저에 보존됩니다.", liveFolderWriteConflict: "연결된 폴더가 Tabula 외부에서 변경되었습니다. 저장하기 전에 충돌을 검토하세요.", liveFolderWriteFailed: "연결된 폴더에 변경 내용을 저장하지 못했습니다.", liveFolderSaved: "연결된 폴더에 저장했습니다.", liveFolderNoChanges: "저장할 변경 사항이 없습니다." },
  ja: { fileCopied: "ファイルをコピーしました。", fileDownloaded: "ファイルをダウンロードしました。", workspaceDownloaded: "ワークスペースをダウンロードしました。", exportFailed: "ファイルに書き出せませんでした。", openFailed: "このワークスペースを開けませんでした。", saveOpenedWorkspaceFailed: "ワークスペースを開きましたが、このブラウザーに保存できませんでした。", unsupportedDrop: "Markdown ファイルをドロップしてください。", confirmLiveFolderDelete: "接続したフォルダーからもこのファイルを削除しますか？", liveFolderPermissionLost: "フォルダーへの書き込み権限が失われました。変更はブラウザーに保存されています。", liveFolderWriteConflict: "接続したフォルダーが Tabula の外部で変更されました。保存前に競合を確認してください。", liveFolderWriteFailed: "接続したフォルダーに変更を保存できませんでした。", liveFolderSaved: "接続したフォルダーに保存しました。", liveFolderNoChanges: "保存する変更はありません。" },
  zh: { fileCopied: "已复制文件。", fileDownloaded: "已下载文件。", workspaceDownloaded: "已下载工作区。", exportFailed: "无法导出为文件。", openFailed: "无法打开此工作区。", saveOpenedWorkspaceFailed: "工作区已打开，但无法保存在此浏览器中。", unsupportedDrop: "请拖放 Markdown 文件。", confirmLiveFolderDelete: "也要从连接的文件夹中删除这些文件吗？", liveFolderPermissionLost: "文件夹写入权限已失效。更改仍保存在此浏览器中。", liveFolderWriteConflict: "连接的文件夹已在 Tabula 外部更改。请先检查冲突。", liveFolderWriteFailed: "无法将更改保存到连接的文件夹。", liveFolderSaved: "已保存到连接的文件夹。", liveFolderNoChanges: "没有需要保存的更改。" },
  es: { fileCopied: "Archivo copiado.", fileDownloaded: "Archivo descargado.", workspaceDownloaded: "Espacio descargado.", exportFailed: "No se pudo exportar a un archivo.", openFailed: "No se pudo abrir este espacio.", saveOpenedWorkspaceFailed: "El espacio se abrió, pero no se pudo guardar en este navegador.", unsupportedDrop: "Suelta un archivo Markdown.", confirmLiveFolderDelete: "¿Eliminar también estos archivos de la carpeta conectada?", liveFolderPermissionLost: "Se perdió el permiso de escritura. Los cambios siguen guardados en este navegador.", liveFolderWriteConflict: "La carpeta conectada cambió fuera de Tabula. Revisa el conflicto antes de guardar.", liveFolderWriteFailed: "No se pudieron guardar los cambios en la carpeta conectada.", liveFolderSaved: "Guardado en la carpeta conectada.", liveFolderNoChanges: "No hay cambios que guardar." },
  fr: { fileCopied: "Fichier copié.", fileDownloaded: "Fichier téléchargé.", workspaceDownloaded: "Espace téléchargé.", exportFailed: "Impossible d’exporter vers un fichier.", openFailed: "Impossible d’ouvrir cet espace.", saveOpenedWorkspaceFailed: "L’espace est ouvert, mais n’a pas pu être enregistré dans ce navigateur.", unsupportedDrop: "Déposez un fichier Markdown.", confirmLiveFolderDelete: "Supprimer aussi ces fichiers du dossier connecté ?", liveFolderPermissionLost: "L’autorisation d’écriture a été perdue. Les modifications restent enregistrées dans ce navigateur.", liveFolderWriteConflict: "Le dossier connecté a changé hors de Tabula. Vérifiez le conflit avant d’enregistrer.", liveFolderWriteFailed: "Impossible d’enregistrer les modifications dans le dossier connecté.", liveFolderSaved: "Enregistré dans le dossier connecté.", liveFolderNoChanges: "Aucune modification à enregistrer." },
  de: { fileCopied: "Datei kopiert.", fileDownloaded: "Datei heruntergeladen.", workspaceDownloaded: "Workspace heruntergeladen.", exportFailed: "Export als Datei fehlgeschlagen.", openFailed: "Dieser Workspace konnte nicht geöffnet werden.", saveOpenedWorkspaceFailed: "Der Workspace wurde geöffnet, konnte aber nicht in diesem Browser gespeichert werden.", unsupportedDrop: "Markdown-Datei hier ablegen.", confirmLiveFolderDelete: "Diese Dateien auch aus dem verbundenen Ordner löschen?", liveFolderPermissionLost: "Die Schreibberechtigung ist verloren gegangen. Änderungen bleiben in diesem Browser gespeichert.", liveFolderWriteConflict: "Der verbundene Ordner wurde außerhalb von Tabula geändert. Prüfe den Konflikt vor dem Speichern.", liveFolderWriteFailed: "Änderungen konnten nicht im verbundenen Ordner gespeichert werden.", liveFolderSaved: "Im verbundenen Ordner gespeichert.", liveFolderNoChanges: "Keine Änderungen zu speichern." },
};

export const getWorkspaceIoCopy = (language: WorkspaceLanguage) => copies[language];
