export const FINAL_REGRESSION_REQUIREMENTS = {
  viewports: ["wide", "narrow", "tablet", "mobile"],
  themes: ["light", "dark"],
  states: [
    "empty-workspace",
    "one-document",
    "many-tabs",
    "visual",
    "source",
    "split",
    "preview",
    "search",
    "right-panel",
    "share",
    "collaboration",
    "error-toast",
  ],
  inputs: ["mouse", "keyboard", "touch", "ime"],
  contracts: [
    "no-clipping",
    "visible-focus",
    "escape",
    "modal-focus-trap",
    "overlay-background-blocked",
    "non-color-state",
    "reduced-motion",
  ],
};

export const FINAL_REGRESSION_COVERAGE = [
  {
    spec: "accessibility-regression.spec.mjs",
    viewports: ["wide", "narrow", "tablet", "mobile"],
    themes: ["light", "dark"],
    states: [
      "empty-workspace",
      "one-document",
      "many-tabs",
      "visual",
      "source",
      "split",
      "preview",
      "search",
      "right-panel",
      "share",
      "error-toast",
    ],
    inputs: ["mouse", "keyboard", "touch", "ime"],
    contracts: [
      "no-clipping",
      "visible-focus",
      "escape",
      "modal-focus-trap",
      "overlay-background-blocked",
      "non-color-state",
      "reduced-motion",
    ],
  },
  {
    spec: "collaboration-capability.spec.mjs",
    viewports: ["wide"],
    themes: ["light", "dark"],
    states: ["collaboration"],
    inputs: ["mouse", "keyboard"],
    contracts: ["non-color-state"],
  },
];
